[package]
name = "infodonnamobil"
version = "0.1.0"
authors = ["Ramazan G. <codmyhesap@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = ["fullstack"] }
markdown = "0.3.0"
mongodb = {version="3.1.0", optional = true }
futures = { version = "0.3.30", optional = true }
serde = { version = "1.0", features = ["derive"], optional=true }
dotenv = "0.15"
tokio = { version = "1.30.0", features = ["full"], optional = true }

[features]
server=["dioxus/server","dep:mongodb","dep:serde","dep:futures","dep:tokio"]
default = []
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
