[package]
name = "infodonnamobil"
version = "0.1.0"
authors = ["Ramazan G. <codmyhesap@gmail.com>"]
edition = "2018"

[dependencies]
dioxus = { version = "*", features = ["fullstack","dioxus-cli-config"] }
markdown = "0.3.0"
mongodb = {version="3.1.0", optional = true }
futures = { version = "0.3.30", optional = true }
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"], optional=true }
serde_json = "1.0"
dotenv = "0.15"
tokio = { version = "1.30.0", features = ["full"], optional = true }
axum = { version = "0.7.0", optional = true }
gloo-timers = { version = "0.3.0", features = ["futures"] }
dioxus-cli-config = { version = "*", optional = false, features = [] }
tower-http = { version = "0.6.2", features = ["cors"] }
features = "0.10.0"
reqwest = { version = "0.12.12", default-features = false, features = [
    "rustls-tls",
    "charset",
    "http2",
    "macos-system-configuration",
    "json"
] }
http = "1.2.0"
dioxus-sdk = { version = "0.6.0", features = ["timing"] }
dioxus-html = { version = "0.6.1", features = ["serialize"]}
[features]
server=["dioxus/server","dep:mongodb","dep:serde","dep:futures","dep:tokio","dep:axum"]
default = ["dep:serde"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
# dioxus-cli-config = ["dep:dioxus-cli-config"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
