[application]

# App (Project) Name
name = "infodonnamobil"

[web.app]

# HTML title tag content
title = "infodonnamobil"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier="com.infodonna.com"
publiser="donnefrivillig"
icon = ["assets/favicon.ico"]
[[web.proxy]]
backend="https://backoffice.koyeb.app/api"
# 
